### ISSUE TITLE
flink on k8s 集成方式

### ISSUE THREAD

**Issue by dpengpeng** [wangyang0918/flink-native-k8s-operator#30]
hello，yang:
 目前在看flink on k8s 的方案选型，发现了你的开源项目，想咨询下你的这个项目实现方式后期会是flink 项目组主推的方式吗？和开源flink 自身的native k8s 的区别是什么？这个operator的方式比网上google等其他公司的operator的优化在什么地方？谢谢

**Comment by wangyang0918** [comment]
目前社区有一个FLIP是要引入一个Flink K8s Operator，可以解答你的疑问，你可以了解下。总之，Flink K8s Operator和native k8s是合作方式，不是相互替代的关系

https://cwiki.apache.org/confluence/display/FLINK/FLIP-212:+Introduce+Flink+Kubernetes+Operator
