### ISSUE TITLE
Ingress Controller Problem

### ISSUE THREAD

**Issue by FuyaoLi2017** [wangyang0918/flink-native-k8s-operator#31]
Hello @wangyang0918 , I noticed a issue for exporting the Flink WebUI through the ingress controller implementation.
https://github.com/wangyang0918/flink-native-k8s-operator/blob/master/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkApplicationController.java#L239

If operator is deployed in `default` namespace, the application is deployed in `flink-test` namespace. The Ingress will be created in default namespace along with the operator. However, such Ingress could not access the rest endpoint in `flink-test` namespace. I think maybe we should maintain a Ingress for each namespace that has a Flink application?

Another small question, do you know how to retrieve the operator deployment name inside the operator java code? I can't find a API in Fabric8io documentation. I want to do this since I am using helm chart, the operator name is a dynamic value injected via `{ .Release.Name }`. I tried to use env variables like FLINK_CONF_DIR (https://github.com/wangyang0918/flink-native-k8s-operator/blob/master/deploy/flink-native-k8s-operator.yaml#L21) to pass the value into the code. Not sure if there are better solutions? Thanks!!!

**Comment by FuyaoLi2017** [comment]
For the second problem, the suggested way is through env varibles. See https://github.com/fabric8io/kubernetes-client/issues/3837

**Comment by FuyaoLi2017** [comment]
For creating Ingress in a different namespace, from the logs I saw it is created, but it is actually not. I will further debug it.

**Comment by FuyaoLi2017** [comment]
I have figured out a solution for this. We should not set owner reference for Ingress resource in a different ns. 
https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/
We can proactively manage the ingress through operator logic and creating corresponding ingress in the namespace that has the FlinkApplication, rather than making them all in the operator namespace.

Also see: https://stackoverflow.com/questions/59844622/ingress-configuration-for-k8s-in-different-namespaces

**Comment by wangyang0918** [comment]
@FuyaoLi2017 Thanks for sharing the result and I have learned a lesson from this. I believe we will benefit from this in the developing [flink-kubernetes-operator](https://github.com/apache/flink-kubernetes-operator) project.
