### ISSUE TITLE
Flink Operator RBAC roles

### ISSUE THREAD

**Issue by FuyaoLi2017** [wangyang0918/flink-native-k8s-operator#33]
Hello Yang,
https://github.com/wangyang0918/flink-native-k8s-operator/blob/master/deploy/flink-native-k8s-operator.yaml#L113
这个apiGroup我不是很理解，这个apiGroup是在哪里定义的，需要在什么地方用到呢？谢谢

**Comment by wangyang0918** [comment]
flink-native-k8s-operator这个应该是不需要的
