### ISSUE TITLE
whether supply a example for this operator about user's flink jar

### ISSUE THREAD

**Issue by z5614036** [wangyang0918/flink-native-k8s-operator#6]

**Comment by FuyaoLi2017** [comment]
This operator only supports application mode for now. If you want to use user's jar. You should write a implementation of session mode yourself.

**Comment by wangyang0918** [comment]
Another alternative is pod template[1], which you could use to download the use jars and artifacts from remote storage. However, you need to enrich the CRD of k8s operator to also support pod template.

[1]. https://ci.apache.org/projects/flink/flink-docs-master/docs/deployment/resource-providers/native_kubernetes/#pod-template

**Comment by wangyang0918** [comment]
I will update the example to use pod template to download the user jar.
