### ISSUE TITLE
How to enable the operator to watch all namespaces and deploy Flink applications to different namespaces?

### ISSUE THREAD

**Issue by FuyaoLi2017** [wangyang0918/flink-native-k8s-operator#9]
I think with the current configurations in the operator, we will be able to deploy the operator in one namespace (`default` namespace in the current implementation) and watch all the CRD changes in that namespaces. Is there a way to let the operator have the ability to watch `FlinkApplication` CRD in all namespaces and deploy Flink applications to different namespaces?

**Comment by wangyang0918** [comment]
Already addressed in #25
